# ——————————————————————————
#         CARTELIZM         
# ——————————————————————————
# 
# Bu dosyada yer alan ayarlar, Cartelizm botlarının kimlik bilgilerini içerir. 
# Tokenlerin girilmemesi ya da yanlış girilmesi durumunda sistem çalışmayacaktır.
# Yanlış bir değişiklik, botun işleyişini etkileyebilir veya tamamen çalışmaz hale getirebilir.
#
# Developer:
# - Discord: @cartelxrd
# - Email: egecanakincioglu@icloud.com

General:
    Voucher: ""
    Supervisor: ""
    Protectives:
        I: ""
        II: ""
        III: ""

# Bu bölümdeki Token ve Channel ayarı istediğiniz kadar arttırılabilir. Token bot sayısını belirtir bir sınırı yoktur.
# Channels ise girilen token sayısıyla orantılı olmalıdır her tokenin bağlanacağı kanalla eşleşmektedir. Bu sebeple orantılı olmalıdır.
# Aksi takdirde sistem çalışmayacak ve hata verecektir.
Welcome:
    Enabled: false
    Tokens: 
        - ""
        - ""
        - ""
    Channels:
        - ""
        - ""
        - ""