# ——————————————————————————
#         CARTELIZM         
# ——————————————————————————
# 
# Bu dosyada yer alan ayarlar, Cartelizm botlarının doğru çalışması için önemlidir. 
# Bu ayarları yalnızca geliştirici veya yetkili bir kullanıcı tarafından değiştirilmesi önerilir. 
# Yanlış bir değişiklik, botun işleyişini etkileyebilir veya tamamen çalışmaz hale getirebilir.
# 
# Lütfen dikkatli olun ve sadece emin olduğunuz ayarları değiştirin. Destek veya bilgi için geliştirici ile iletişime geçin.
#
# Developer:
# - Discord: @cartelxrd
# - Email: egecanakincioglu@icloud.com

Logger:
    Info: "INFO"
    Warn: "WARN"
    Error: "ERROR"

Console:
    Prefix: "Sistem"