# ——————————————————————————
#         CARTELIZM         
# ——————————————————————————
# 
# Bu dosyada yer alan ayarlar, Cartelizm botlarının doğru çalışması için önemlidir. 
# Bu ayarları yalnızca geliştirici veya yetkili bir kullanıcı tarafından değiştirilmesi önerilir. 
# Yanlış bir değişiklik, botun işleyişini etkileyebilir veya tamamen çalışmaz hale getirebilir.
# 
# Lütfen dikkatli olun ve sadece emin olduğunuz ayarları değiştirin. Destek veya bilgi için geliştirici ile iletişime geçin.
#
# Developer:
# - Discord: @cartelxrd
# - Email: egecanakincioglu@icloud.com

ClientManager:
    VoucherPath: "./Clients/Voucher/Cartelizm.ts"
    SupervisorPath: "./Clients/Supervisor/Cartelizm.ts"
    ProtectivesPath:
        I: "./Clients/Protective/I/Cartelizm.ts"
        II: "./Clients/Protective/II/Cartelizm.ts"
        III: "./Clients/Protective/III/Cartelizm.ts"

HandlerPaths:
    Event:
        Voucher: "./Clients/Voucher/Events"
        Supervisor: "./Clients/Supervisor/Events"
        Protectives:
            I: "./Clients/Protection/I/Events"
            II: "./Clients/Protection/II/Events"
            III: "./Clients/Protection/III/Events"
    Command:
        Voucher: "./Clients/Voucher/Commands"
        Supervisor: "./Clients/Supervisor/Commands"
        Protectives:
            I: "./Clients/Protection/I/Commands"
            II: "./Clients/Protection/II/Commands"
            III: "./Clients/Protection/III/Commands"

GlobalClientNames:
    Voucher: "Voucher"
    Supervisor: "Supervisor"
    Protectives:
        I: "Protective I"
        II: "Protective II"
        III: "Protective III"